import "./globals.css";
import { Navbar } from "@/app/ui/Nabvar";
import { montserrat, workSans, openSans } from "@/app/ui/fonts";
import { Footer } from "@/app/ui/Footer";

export const metadata = {
  title: "CYTSA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={montserrat.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
